# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=140),
        ),
    ]
