# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-24 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200420_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BinaryField(),
        ),
    ]
