# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200424_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_as_base64',
            field=models.TextField(blank=True),
        ),
    ]
